Fix the deprecation warning when running `cargo t`
by upgrading `bindgen` to v0.60.1, while also disabling
unused features "clap" and "logging" for bindgen.

Sample Error:

```
error: reference to packed field is unaligned
    --> /Users/nobodyxu/Dev/graphicsmagick-rs/target/debug/build/graphicsmagick-sys-8cd71f4fdbf4f847/out/b
indings.rs:5786:18
     |
5786 |         unsafe { &(*(::std::ptr::null::<_OSUnalignedU16>())).__val as *const _ as usize },
     |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |
     = note: `#[deny(unaligned_references)]` on by default
     = warning: this was previously accepted by the compiler but is being phased out; it will become a har
d error in a future release!
     = note: for more information, see issue #82523 <https://github.com/rust-lang/rust/issues/82523>
     = note: fields of packed structs are not properly aligned, and creating a misaligned reference is und
efined behavior (even if that reference is never dereferenced)
     = help: copy the field contents to a local variable, or replace the reference with a raw pointer and
use `read_unaligned`/`write_unaligned` (loads and stores via `*p` must be properly aligned even when using
 raw pointers)
```

Signed-off-by: Jiahao XU <Jiahao_XU@outlook.com>